const ADD_USER = 'ADD_USER'
const SET_USER = 'SET_USER'
const ADD_ERRORS = 'ADD_ERRORS'
const CLEAR_ERRORS = 'CLEAR_ERRORS'

const ADD_BREWERIES = 'ADD_BREWERIES'
const LOADING_BREWERIES = 'LOADING_BREWERIES'
const SELECTED_BREWERY = 'SELECTED_BREWERY'

const LOADING_REVIEWS = 'LOADING_REVIEWS'
const SET_REVIEW = 'SET_REVIEW'
const SET_REVIEWS = 'SET_REVIEWS'
const ADD_REVIEW = 'ADD_REVIEW'
const SELECTED_REVIEW = 'SELECTED_REVIEW'








export {
    ADD_USER,
    SET_USER,
    ADD_ERRORS,
    CLEAR_ERRORS,
    ADD_BREWERIES,
    LOADING_BREWERIES,
    SELECTED_BREWERY,
    LOADING_REVIEWS,
    SET_REVIEW,
    SET_REVIEWS,
    ADD_REVIEW,
    SELECTED_REVIEW
}